feat(NavBarLink)!: renamed to NavBarButton; improved styles
prenda-school/prenda-spark pull request #166
Opened 2021-07-22 19:28 UTC by slingner

Related to issue #74

Updated NavbarLink is now NavBarButton.
Made a new story specifically for NavBarButton (took out of navbar story), added variations for all States.

2021-07-22 20:36 UTC, WilliamKelley requested changes
Please validate all styles with Figma again. Icon size doesn't match:

PR:
![image](https://user-images.githubusercontent.com/25781782/126706140-cec22f72-ec69-47a1-8e84-723c757bb61f.png)

Figma:
![image](https://user-images.githubusercontent.com/25781782/126706147-93082ec8-145e-4c5f-92c6-a14d382e3c01.png)

2021-07-22 22:05 UTC, WilliamKelley requested changes
Looks great! just little things.

I'll also suggest two things related to the NavBar story that isn't the responsibility of this PR, but you can choose to fix them:
- use correct new icons for the nav bar buttons
- match the notifications button styling in figma (less space between the icon and '0' -- will require a one-off style customization.

2021-07-22 22:05 UTC, WilliamKelley commented on libs/spark/src/NavBarButton.tsx
> +      fontSize: '2rem', // small/medium/large for icons is 16px/24px/32px
```suggestion
      fontSize: '2rem',
```

2021-07-22 22:05 UTC, WilliamKelley commented on libs/spark/stories/navbarbutton.stories.tsx
> +export const AllHover = AllTemplate.bind({});
```suggestion
export const All = AllTemplate.bind({});

export const AllDisabled = AllTemplate.bind({});
AllDisabled.args = { disabled: true };

export const AllHover = AllTemplate.bind({});
```

etc. for readability

2021-07-22 22:05 UTC, WilliamKelley commented on libs/spark/test/navbar.spec.tsx
>  describe('Button', () => {
Not this PR's fault, but it can fix it

```suggestion
describe('NavBar', () => {
```

2021-07-23 19:13 UTC, slingner commented
> Looks great! just little things.
> 
> I'll also suggest two things related to the NavBar story that isn't the responsibility of this PR, but you can choose to fix them:
> 
> * use correct new icons for the nav bar buttons
> * match the notifications button styling in figma (less space between the icon and '0' -- will require a one-off style customization.

I ended up added a negative margin to get the 0 closer to the icon, let me know if you have a cleaner solution in mind!

2021-07-23 20:55 UTC, WilliamKelley commented
> I ended up added a negative margin to get the 0 closer to the icon, let me know if you have a cleaner solution in mind!

That does the job! But I think we should set the example to not use inline styles. Instead,
```jsx

import { withStyles } from '@material-ui/core';

const CustomToolbar = withStyles({
  root: {
    gap: 8,
  },
})(Toolbar);

const InboxNavBarButton = withStyles({
  root: {
    marginLeft: 'auto',
  },
  startIcon: {
    marginRight: 2,
  },
})(NavBarButton);
```

2021-07-23 21:06 UTC, WilliamKelley requested changes

2021-07-23 21:06 UTC, WilliamKelley commented on libs/spark/stories/navbar.stories.tsx
>          style={{ marginLeft: 'auto' }}
```suggestion
```

2021-07-23 21:07 UTC, WilliamKelley approved these changes

2021-07-23 21:29 UTC, shadoath approved these changes

2021-07-23 22:23 UTC, merged