fix(spark-icons): camelCase hyphenated path attrs
prenda-school/prenda-spark pull request #184
Opened 2021-08-09 21:27 UTC by seigler

Resolves #183

2021-08-09 21:48 UTC, WilliamKelley commented
Although I'd like the fix to be in Figma, it'll be fine to monkey patch since its only our few custom icons.

But you'll also need to modify the icons builder script to camel case these attributes if it finds them on the svg. I think it's clear in the file where that's done. That way in the future, we won't have to monkey patch them again.

2021-08-09 21:49 UTC, WilliamKelley requested changes
see previous comment

2021-08-09 22:18 UTC, WilliamKelley approved these changes

2021-08-10 00:51 UTC, shadoath approved these changes

2021-08-10 13:12 UTC, merged